name: Deploy Frontend

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

      - name: Build and push escape-frontend Docker image
        run: |
          docker build -t semmmi/escape-frontend:latest .
          docker push semmmi/escape-frontend:latest

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm

      - name: Set Vercel Environment Variables
        run: |
          curl -X PATCH https://vercel.com/tpal0719s-projects/${{ secrets.VERCEL_PROJECT_ID }}/env \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '[
            {
              "key": "VUE_APP_CORE_API_URL",
              "value": "'"${{ secrets.VUE_APP_CORE_API_URL }}"'",
              "target": ["production", "preview"]
            },
            {
              "key": "VUE_APP_ADMIN_API_URL",
              "value": "'"${{ secrets.VUE_APP_ADMIN_API_URL }}"'",
              "target": ["production", "preview"]
            },
            {
              "key": "VUE_APP_MANAGER_API_URL",
              "value": "'"${{ secrets.VUE_APP_MANAGER_API_URL }}"'",
              "target": ["production", "preview"]
            },
            {
              "key": "VUE_APP_CONSUMER_API_URL",
              "value": "'"${{ secrets.VUE_APP_CONSUMER_API_URL }}"'",
              "target": ["production", "preview"]
            },
            {
              "key": "VUE_APP_RESERVATION_API_URL",
              "value": "'"${{ secrets.VUE_APP_RESERVATION_API_URL }}"'",
              "target": ["production", "preview"]
            },
            {
              "key": "VUE_APP_SEARCH_API_URL",
              "value": "'"${{ secrets.VUE_APP_SEARCH_API_URL }}"'",
              "target": ["production", "preview"]
            }
          ]'


      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
