name: Deploy Frontend

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16'  # Vue 프로젝트에 맞는 Node.js 버전

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: /tmp/vue-app

      - name: Verify downloaded artifacts
        run: |
            echo "Listing contents of /tmp/vue-app:"
            ls -al /tmp/vue-app

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           port: 22
           script: |
             rm -rf /var/www/html/*
             scp -r dist/* /var/www/html/
             sudo systemctl restart nginx