name: Deploy Frontend

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16'  # Vue 프로젝트에 맞는 Node.js 버전

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm update
          npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
          VITE_APP_CORE_API_URL: ${{ secrets.VITE_APP_CORE_API_URL}}
          VITE_APP_ADMIN_API_URL: ${{ secrets.VITE_APP_ADMIN_API_URL}}
          VITE_APP_MANAGER_API_URL: ${{ secrets.VITE_APP_MANAGER_API_URL}}
          VITE_APP_CONSUMER_API_URL: ${{ secrets.VITE_APP_CONSUMER_API_URL}}
          VITE_APP_RESERVATION_API_URL: ${{ secrets.VITE_APP_RESERVATION_API_URL}}
          VITE_APP_SEARCH_API_URL: ${{ secrets.VITE_APP_SEARCH_API_URL}}
