name: Deploy Frontend
env:
  VERCEL_ORG_ID : ${{ secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID : ${{ secrets.VERCEL_PROJECT_ID}}
  VUE_APP_CORE_API_URL : ${{ secrets.VUE_APP_CORE_API_URL}}
  VUE_APP_ADMIN_API_URL  : ${{ secrets.VUE_APP_ADMIN_API_URL}}
  VUE_APP_MANAGER_API_URL  : ${{ secrets.VUE_APP_MANAGER_API_URL}}
  VUE_APP_CONSUMER_API_URL  : ${{ secrets.VUE_APP_CONSUMER_API_URL}}
  VUE_APP_RESERVATION_API_URL  : ${{ secrets.VUE_APP_RESERVATION_API_URL}}
  VUE_APP_SEARCH_API_URL  : ${{ secrets.VUE_APP_SEARCH_API_URL}}
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Install Vercel CLI (Optional if using Vercel)
        run: npm install --global vercel@latest

      - name: Deploy to Vercel (Optional if using Vercel)
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm